### ISSUE TITLE
Is this app a hard fork or a soft fork of Retro?

### ISSUE THREAD

**Issue by puelp** [MuntashirAkon/Metro#124]
Is this app a hard fork of Metro, where you have your own roadmap and development of bugfixes and new features?

Or is this a soft fork like Firefox & Fennec F-Droid, where the focus is on taking out the proprietary bits but no heavy development beyond that?

**Comment by MuntashirAkon** [comment]
This is a _soft fork_ by your definition. Expect no major features but only occasional bug fixes and minor features, that is, if I get enough time to take a look at them. Personally, I think the app offers no real improvements over existing apps such as Music Player GO or Phonograph (and its derivatives), other than a more customisable UI, and therefore, I no longer use the app myself. Earlier a discontinuation of Metro was announced, but with increasing requests from the users, including a few friends, I decided to provide somewhat occasional updates. However, recently, Retro developers have changed their stance on F-Droid and decided to [publish](https://gitlab.com/fdroid/rfp/-/issues/2120) a F-Droid specific build. I am basically waiting to see what happens with the RFP. But it's already been two months and the issue seems to be completely stale. I will wait few more weeks before the next release to see what happens.

---
For the future viewers, here is the announcement that I posted earlier on [Telegram](https://t.me/AppManagerChannel/148):

<details>

**Announcing the Discontinuation of Metro.**

You may be already aware that Metro hasn’t been receiving update for some time. I’ve already made some changes but didn’t get the time to provide an update. So, you may get another (and the final) update soon.

**Why I started it in first place?**
Retro Music is the best open source (but non-libre) music player for Android with many features and screens, and an app that I used occasionally. Therefore, I thought it would be nice to put it on F-Droid by making it truly open source. So, I did it.

**What went wrong?**
Retro Music or Phonograph or any other forks of Phonograph, or any open source music app for Android relies on Android Media Store, which has many limitations, and the false-positive ratio seems to be ever on the increase (in fact, most of the music files I have in my phone aren’t recognized by the stupid Media Store). This situation is very familiar to the Poweramp users, which, unlike these music players, does not rely on Media Store. As a developer, my purpose of developing an open source app is to use it on my device in a regular basis, and Retro/Metro isn’t something I can use because of this limitation. So, I was very disappointed, and my disappointment led to the discontinuation of the app.

**What’s the future of open source music player for Android?**
Personally, I don’t see any future right now. Of course, there are many open source music players available to date, but every app I’ve ever tested relies on Media Store which is a deal-breaker. So, for me, Poweramp is currently the best option. However, in the future, I might work on an app that wouldn’t rely on Media Store, but the chances are very remote unless I see interests from other developers and contributors, because massive projects like this cannot be succeeded without massive collaboration. If you are such a developer or contributor, you can send me an email at muntashirakon-at-riseup-dot-net specifying your field of interests i.e., a developer should have previous working knowledge of Java, C/C++ and JNI and other contributions should be purely on marketing and finance. DO NOT bother me unless you fall in any of this category.

I know this is a disappointing news, but this is the reality.
</details>

**Comment by coxackie** [comment]
Retro seems to have been discontinued... Could you please at least rebase your version to the last commit of the dev branch so we can get all the latest fixes and updates?

**Comment by MuntashirAkon** [comment]
> Retro seems to have been discontinued... Could you please at least rebase your version to the last commit of the dev branch so we can get all the latest fixes and updates?

Maybe, when I am at leisure. But don't count on it as I'm always busy with work and other projects. However, earlier other contributors have come forward. Basically, the project is on low maintenance mode because I don't use the app myself. The idea was to keep it afloat until Retro is on F-Droid which never happened till now.

**Comment by puelp** [comment]
Thank you for the detailed response.

If this app has de-facto been discontinued and according to @coxackie the source app Retro is dead as well, then as it appears to be time to switch to an alternative, I hope that you will not mind my asking you a related follow-up question.

I asked it here: https://github.com/MuntashirAkon/Metro/issues/140 but maybe I should have asked it here instead?
