### ISSUE TITLE
Warning notification at launch 

### ISSUE THREAD

**Issue by thetrashcanhero** [MuntashirAkon/Metro#160]
**Describe the bug**
A pop up appears at every launch of the app with a warning that the app is a copy if retro music and asks to download retro from the play store instead. Another pop up appears asking if I want to open in the play store or f-droid. 

**How To Reproduce**
1.  Make sure app is not already running
2. Open the app and warning appears

**Expected behavior**
No warning notification to appear.

**Device info:**
 - Device: Pixel 7
 - Android version: GrapheneOS 
 - App version 6.0.4

**Comment by Golbinex** [comment]
Considering that Retro Player is now available on F-Droid and it even offers Pro features,  this soft fork is currently not needed unless situation changes.

**Comment by Golbinex** [comment]
> > Considering that Retro Player is now available on F-Droid and it even offers Pro features, this soft fork is currently not needed unless situation changes.
> 
> I don't want to use a FOSS music player that has an internet connection and uses Google's proprietary libraries. Metro player Solves this.

Afaik F-Droid doesn't allow any proprietary libraries in builds, so F-Droid flavor shouldn't have them.

Internet connection is unfortunately still present, my custom ROM allows blocking it though.

The developer stated [here](https://github.com/MuntashirAkon/Metro/issues/124#issuecomment-1345441566) that this project is low priority and the idea was to maintain it until Retro gets released on F-Droid, which now happened.

**Comment by Turhvjbufv** [comment]
Idk about you I'm here for pro unlocked

**Comment by SleepDaemon** [comment]
> > > Considering that Retro Player is now available on F-Droid and it even offers Pro features, this soft fork is currently not needed unless situation changes.
> > 
> > 
> > I don't want to use a FOSS music player that has an internet connection and uses Google's proprietary libraries. Metro player Solves this.
> 
> Afaik F-Droid doesn't allow any proprietary libraries in builds, so the F-Droid flavor shouldn't have them.
> 
> Internet connection is unfortunately still present, my custom ROM allows blocking it though.
> 
> The developer stated [here](https://github.com/MuntashirAkon/Metro/issues/124#issuecomment-1345441566) that this project is low priority and the idea was to maintain it until Retro gets released on F-Droid, which now happened.

its not on f-droid repo, its on izzy-droid repo. Which allows these google crap dependencies. So no its not the solution we want and wont be, as long they use google service dependencies and try to have internet connection. This fork removes them and unlocks the premium stuff. So yeah, I don't this should be hard to fix considering its just a pop up toast.

**Comment by RedCyberPandaz** [comment]
Yes, what I have seen is it trying to open the google play store and it has little messages on the bottom saying "Warning this is a copy of Retro Music player" "Instead of using this copy by a dumb person who didn't even bother..." and its cut off. And then "Support us by downloading the original version from play store". So I guess the devs of "Retro Music Player" have devolved into name calling with improper toast notification sizes.

**Comment by RedAnon** [comment]
Bold of him calling someone stupid when he can't even make sure to not exceed the character limit. "to remo..."? To remove what, dumbass.

![ironic](https://user-images.githubusercontent.com/38892787/229355297-d87de249-1864-4f0a-ba1e-d26b2125824b.png)

**Comment by zoroya1** [comment]
>the idea was to maintain it until Retro gets released on F-Droid, which now happened.

Where it happened ? Retro got Izzyondroid repo afaik, and dev. mentioned fdroid repo, Retro is still not on fdroid.

**Comment by zoroya1** [comment]
It ended like this "a dumb person who didn't even bother to remove this code"

I used landscape mode specially to read this, sad to see this type of name shaming and after all these releases, i mean where were you (retro dev) before ?

**Comment by zoroya1** [comment]
> Bold of him calling someone stupid when he can't even make sure to not exceed the character limit. "to remo..."? To remove what, dumbass.
 It ended like this "a dumb person who didn't even bother to remove this code"

I used landscape mode specially to read this, sad to see this type of name shaming and after all these releases, i mean where were you (retro dev) before ?

**Comment by zoroya1** [comment]
It is on fdroid now.

**Comment by zoroya1** [comment]
> its not on f-droid repo, its on izzy-droid repo. 

Retro is now on fdorid, (3/4/2023 realease)

**Comment by Golbinex** [comment]
@SleepDaemon @zoroya1 IT IS in [official F-Droid repo](https://f-droid.org/en/packages/code.name.monkey.retromusic/) which I presume is also the reason why they included that code (which could be a lot more malicious if they wanted to)

**Comment by RedCyberPandaz** [comment]
> > its not on f-droid repo, its on izzy-droid repo.
> 
> Retro is now on fdorid, (3/4/2023 realease)

Yeah but I dont want this.

![Screenshot_20230402-110031_F-Droid](https://user-images.githubusercontent.com/107568557/229361470-88d6288c-41f9-4f6c-bc1c-e1759404d480.jpg)

I want the foss one that doesnt rely on all of that.

**Comment by Golbinex** [comment]
> > the idea was to maintain it until Retro gets released on F-Droid, which now happened.
> 
> Where it happened ? Retro got Izzyondroid repo afaik, and dev. of Metro mentioned fdroid repo, ~~Retro is still not on fdroid ~~
> 
> So, today it came on fdorid, i am sure it will have google libraries reomoved, but i don't think premium features are unlocked like metro has. They only have google's way of doing purachses so we can't use it in degoogled device

I didn't encounter any locked features. It's shown as "Pro version". Not sure if F-Droid has any policy about Pro features so they had to unlock them.
![Screenshot_20230402-170517_Retro Music](https://user-images.githubusercontent.com/62813600/229361991-adc132ff-ce45-448a-8204-8639e2c60bc7.png)


> > > its not on f-droid repo, its on izzy-droid repo.
> > 
> > 
> > Retro is now on fdorid, (3/4/2023 realease)
> 
> Yeah but I dont want this.
> 
> ![Screenshot_20230402-110031_F-Droid](https://user-images.githubusercontent.com/107568557/229361470-88d6288c-41f9-4f6c-bc1c-e1759404d480.jpg)
> 
> I want the foss one that doesnt rely on all of that.

Where do you see these Anti-features? I don't see any on my F-Droid app.

**Comment by RedCyberPandaz** [comment]
> > > the idea was to maintain it until Retro gets released on F-Droid, which now happened.
> > 
> > 
> > Where it happened ? Retro got Izzyondroid repo afaik, and dev. of Metro mentioned fdroid repo, ~~Retro is still not on fdroid ~~
> > So, today it came on fdorid, i am sure it will have google libraries reomoved, but i don't think premium features are unlocked like metro has. They only have google's way of doing purachses so we can't use it in degoogled device
> 
> I didn't encounter any locked features. It's shown as "Pro version". Not sure if F-Droid has any policy about Pro features so they had to unlock them. ![Screenshot_20230402-170517_Retro Music](https://user-images.githubusercontent.com/62813600/229361991-adc132ff-ce45-448a-8204-8639e2c60bc7.png)
> 
> > > > its not on f-droid repo, its on izzy-droid repo.
> > > 
> > > 
> > > Retro is now on fdorid, (3/4/2023 realease)
> > 
> > 
> > Yeah but I dont want this.
> > ![Screenshot_20230402-110031_F-Droid](https://user-images.githubusercontent.com/107568557/229361470-88d6288c-41f9-4f6c-bc1c-e1759404d480.jpg)
> > I want the foss one that doesnt rely on all of that.
> 
> Where do you see these Anti-features? I don't see any on my F-Droid app.

I use izzyondroid repo alongside F-droid repo. Idk which one its pulling from but both the f-droid one and izzyondroid one says the same thing just allows different downloads. But judging by their repo thats connected to the fdroid store page and the issues tracker, people are saying you still have to purchase the full version through google play store. But generally try it if you want, I think this issue is more about the fact that bit of code needs removed from the app.

**Comment by SleepDaemon** [comment]
let me clarify this, Retro is on IzzyDroid **not** F-Droid. Izzydroid allows google play services.

it does say f-droid but I think that's the one without Pro purchase option. Instead if you want to get Pro you have to use Izzydroid version which allows google play services.
![tempFileForShare_20230402-183144](https://user-images.githubusercontent.com/88533953/229363008-4e2da8f0-1d29-4078-83ce-9985b61aaabe.jpg)

**Comment by SleepDaemon** [comment]
you can see under "Anti-features" it says has non-free network and promotes non-free network

**Comment by SleepDaemon** [comment]
also gonna unsubscribe from this issue, to many emails

**Comment by 0xMANFRE** [comment]
@prathameshmm02
Mr More, [your commit on the RetroMusicPlayer repo](https://github.com/RetroMusicPlayer/RetroMusicPlayer/commit/cee51eb2cce6add412e1556038b4e4d6396b3ec8) about adding a "plagiarism check" when launching a fork of the app is both unethical and downright disrespectful.
People like me use this fork because it's completely offline and fully libre, it does not contain any proprietary SDKs.
If you wanted people to exclusively use your app and do not allow forks, you should have chosen to publish the code under a different licence instead of GPL-3, or even kept the app proprietary.
I thank you for the music player that you and many other people have developed, but I have no respect for what you have done in this instance.

**Comment by puelp** [comment]
Let's clear some few things up because this thread is getting cluttered now, with confusing misinformation.

1. With the latest repo refresh, Retro (the original) and Metro (the fork) are now BOTH available on the **main** F-Droid repo.
2. The anti-feature warnings for Retro (the original) is from the unofficial Izzy repo, NOT the main F-Droid repo. On the main F-Droid repo, neither Retro (the original) nor Metro (the fork) have any anti-feature warnings.
3. On the main F-Droid repo, Retro (the original) requires the Internet permission, while Metro (the fork) does not. This lack of an Internet access permission is important for privacy-conscious people, which gives Metro (the fork) a selling point and a reason to exist, even if the two apps are otherwise 99.9% identical.

And now here's my speculation regarding the intrusive "Warning! This is a copy of Retro..." alerts. My thinking is that they are intended for the myriad of clones on the Play Store that simply take Retro's code, insert ads, give zero attribution, and then profit off of the Retro dev's work.

Ergo, it is NOT intended for Metro, because that would make no sense; Metro makes no secret of the fact that it is a fork of Retro and doesn't profit off of it in any way. Metro simply got caught in the cross-fire, that's all.

My conclusion is that we all just have to be patient and wait for @MuntashirAkon  to remove the relevant code and push an update, and that'll be the end of it.

**Comment by MuntashirAkon** [comment]
@puelp: Thanks for mentioning me. I'm not actually subscribed to receive any notifications from the repository for the reasons mentioned in the linked issue. If you didn't mention me, it might take sometime before I noticed it. Here's my comment on the situation and the issue itself:

Metro was forked and published on F-Droid (ergo there's no binary releases other than the ones built by F-Droid) at a time when no good music player existed on F-Droid (okay, maybe other than [the forks of] Phonograph). There should be no doubt about the fact that this project has no intention of gaining profits of any sort from any place (I do not have any accounts in any app stores at all). It all began when the maintainers refused to publish the app on F-Droid, and I thought that it wouldn't hurt me if I forked and published a pure FOSS version of the app licensed under GPL-3.0-or-later (I wish I knew how wrong I was). There are many such apps already present in F-Droid. One good example is Insular which, I guess, most people in this thread may have used or tried, at least. Even then, one contributor asked the original developer for a donation link outside Play Store which could be included in this app, which too was refused.

All this has been done in _good faith_. Yet, for some strange reasons, some of the developers still believe that I did an evil thing by copy-thefting their _copylefted_ work. They even went on to block a few Metro users from their official Telegram channels. These behaviours were quite disappointing and difficult to forget. However, due to increasing requests for a new build and with the help of some contributors, I was able to publish a few more releases, and promised to discontinue the app once the official one is on F-Droid **which I shall do** after fixing this issue. If anybody else wants to take over the development, I shall be happy to assist, but I cannot take the blames anymore.

Regarding this issue, I've not noticed it because I didn't built a release version. But including such message is something I've never seen in my nine years of open source development. I don't know if others have observed such irresponsible behaviour, which, at this point, makes it clear that the maintainers of Retro Music have no respect for open source community nor the license it opted, which also means that this hostile and non-free sentiments shared by the maintainers cannot be accepted by me as an advocate of FOSS and reproducible builds.

Let me know what you think. Thanks.

**Comment by CalebJohnathen** [comment]
Seeing the developers acting so childish just reinforces the fact that forks of foss apps like this one is important.

**Comment by puelp** [comment]
Again, I don't think that Metro is the one being targeted.

Just look at this list of Retro copycats (compiled by the Retro dev): https://docs.google.com/spreadsheets/d/1l0VQuRs-n6DYplkUCF7E_m5EODQvKwenYrczCoB1Kpo/

It's quite a lengthy list, and I imagine a never-ending game of whack-a-mole of getting them taken down (by which time I assume the copycats already made a profit from ads).

It's unfortunate that Metro, a legitimate fork, was caught in the crossfire, but at least it's understandable why the Retro dev did what he did.

Do you plan on removing the warnings and pushing a new release?

**Comment by chwt163** [comment]
> 

I don't want too

**Comment by chwt163** [comment]
> > Considering that Retro Player is now available on F-Droid and it even offers Pro features, this soft fork is currently not needed unless situation changes.
> 
> I don't want to use a FOSS music player that has an internet connection and uses Google's proprietary libraries. Metro player Solves this.

I don't want too，I like metro.

**Comment by zoroya1** [comment]
Fdroid version of Metro shows 1 tracker : `custom activity on crash` is there chances that devs of Retro included that in code that's why i gave those messages ?

**Comment by MuntashirAkon** [comment]
> It's quite a lengthy list, and I imagine a never-ending game of whack-a-mole of getting them taken down (by which time I assume the copycats already made a profit from ads).

But would putting such a message fix the issue? It certainly isn't. In Google Play Store, I've seen some developers publishing hundreds of open source apps. Google frankly don't care about licensing, and they especially hate GPL-like licenses. Nowadays, they even went on to silently installing their apps through their malware delivery store.

> Seeing the developers acting so childish just reinforces the fact that forks of foss apps like this one is important.

Most certainly. But you need a developer who can actually manage enough time. I maintain far too many apps already.

> Fdroid version of Metro shows 1 tracker : `custom activity on crash` is there chances that devs of Retro included that in code that's why it gave those messages ?

**Custom activity on crash** is on the ETIP list. Frankly speaking, this library is incapable of _phoning home_ without the help of another library or custom implementation. Therefore, it shouldn't be considered a tracker in itself.

**Comment by zoroya1** [comment]
> Most certainly. But you need a developer who can actually manage enough time. I maintain far too many apps already.

If someone with coding knowledge and cintributor can take up on metro, it will be awesome. **Symohony** is also a foss offline music player which is actively maintained, if someone integrates metro's cutomization and other features via metro's code, it will greatly benefit both as symphony is actively maintained + features of metro + foss, and no bothersome pop ups of retro.

> > Fdroid version of Metro shows 1 tracker : `custom activity on crash` is there chances that devs of Retro included that in code that's why it gave those messages ?
> 
> **Custom activity on crash** is on the ETIP list. Frankly speaking, this library is incapable of _phoning home_ without the help of another library or custom implementation. Therefore, it shouldn't be considered a tracker in itself.

Makes sense.

**Comment by krolyxon** [comment]
Its this [file](https://github.com/MuntashirAkon/Metro/blob/dev/app/src/main/java/code/name/monkey/retromusic/util/PlagiarismUtil.kt) causing the issue.

```java
  // Log these things to console, if the plagiarizer even cares to check it
  Log.d("Retro Music", "What are you doing with your life?")
  Log.d("Retro Music", "Stop copying apps and make use of your brain.")
  Log.d("Retro Music", "Stop doing this or you will end up straight to hell.")
  Log.d("Retro Music", "To the boiler room of hell. All the way down.")
```

What the hell is the retro music's dev even thinking? The code is literally licensed under gpl v3 and expect others not to use it?

**Comment by RedAnon** [comment]
```java
Log.d("Retro Music", "What are you doing with your life?")
Log.d("Retro Music", "Stop copying apps and make use of your brain.")
```
Heavy "DO NOT REDEEM" vibes.

**Comment by 0xMANFRE** [comment]
> Fixed via [bfa08fc](https://github.com/MuntashirAkon/Metro/commit/bfa08fc032750c7c3c6e0a905e01cbe148e8b1c9)

Thank you. Do you know how many days does it usually takes for F-droid to build the app on their repo?

**Comment by Seb3thehacker** [comment]
@0xMANFRE I believe it takes about 2-3 days now.

**Comment by MuntashirAkon** [comment]
> Do you know how many days does it usually takes for F-droid to build the app on their repo?

I don't know. But last time it took more than two weeks.

**Comment by 0xMANFRE** [comment]
> > I don't know. But last time it took more than two weeks.
> 
> Where can we get the latest (6.1.0) version of metro music player, to install.

Metro releases are only available through the official F-droid repo.
If you want to get access as soon as possible, you can compile from source code. If you do this, you must first uninstall the version you have on your smartphone because your app signature will be different from the one signed by the F-droid repo.

**Comment by mjcassim** [comment]
> > ```java
> > Log.d("Retro Music", "What are you doing with your life?")
> > Log.d("Retro Music", "Stop copying apps and make use of your brain.")
> > ```
> Clearly, the developer of Retro has major problems understanding FOSS values. It's not a copy, it's a fork. This is how OPEN SOURCE WORKS. Retro makes use of proprietary libraries, has paid features, uses a license that allows others to fork and distribute, and then it has this kind of behavior.
> 
> I think Retro's developer wanted to develop a proprietary app and got it wrong...

I was literally just about to say this lol..

**Comment by Venderbad** [comment]
Guys I think we can stop blaming the devs od Retro since they just wanted to humiliate the damn copycats on Play Store but accidentally targeted Metro as well. I completely agree @puelp 's theory.

I posted an issue on Retro's repo yesterday and the dev who added `plagiarism utils` in the upstream code replied:

> Actually, that was to prevent having hundreds of copies on Play store. My thinking was, if someone forks this repo, they will test it at least once and see there's an error, and will try to remove it, as opposed to the copycats who just put ads to make money out of this app and might just give up trying to figure out the error. Well, tbh my thinking was not so clever. I'll remove this. Sorry for the trouble.

Then the dev removed the plagiarism utils in the upstream completely. I think you guys can be pacified now.

**Comment by krolyxon** [comment]
he could have avoided all of it by mentioning this earlier. anyways at the end we are good now.

**Comment by DioEgizio** [comment]
How is this not on fdroid yet?
