### ISSUE TITLE
Differences between Metro and RetroMusicPlayer?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [MuntashirAkon/Metro#5]
can i have a list of differences between Metro and RetroMusicPlayer?

**Comment by MuntashirAkon** [comment]
Other than Google play being removed and all pro features being free, there's no major difference between the two yet (well, except some bug fixes). I did that in order to publish it to F-Droid. But it is my intention to use a custom music scanner other than the one comes with Android as it tends to miss some music files.

**Comment by TheEvilSkeleton** [comment]
sure, i'll submit a merge request explaining the differences between Metro and RetroMusicPlayer

**Comment by MuntashirAkon** [comment]
The irony is that I find many nice applications which are licensed under GNU-GPL but doesn't actually understand the GNU philosophy.

**Comment by TheEvilSkeleton** [comment]
LMAO IKR. this is quite common in Android applications unfortunately

**Comment by TheEvilSkeleton** [comment]
@MuntashirAkon if you want, you can keep this issue open, and you can update me everytime you add something that will make it differ from RetroMusicPlayer to Metro, so i can PR

**Comment by MuntashirAkon** [comment]
There's hardly any chance of implementing new features (except bug fixes) right now as my current focus is on **App Manager** and due to the fact that Kotlin is completely a new experience for me.

**Comment by MuntashirAkon** [comment]
Ok, I'm currently working on improving text sizes and formatting a bit (See #21).
